# Generated by Django 5.1.4 on 2024-12-30 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brand',
            new_name='Category',
        ),
    ]
